### ISSUE TITLE
SUPPORT: need to update the "project chat" link to target AfterLutz Discord

### ISSUE THREAD

**Issue by Aaronontheweb** [AfterLutz/.github#1]
https://github.com/AfterLutz/.github/blob/main/SUPPORT.md - currently targets the original Discord, which no one has admin access to any longer.

**Comment by malclear** [comment]
I'd like to put this on hold. It may be that the ownership of the Akkatecture Discord can be reassigned. It might be something that Lutando's family can help with, and we do have the ability to continue discussions there.

**Comment by Aaronontheweb** [comment]
Sounds good
